### ISSUE TITLE
Handle amendments

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-campfin#14]
- [ ] Create DonorContribution model.
- [x] Bulk deactivate / insert amended filings.
- [x] Build model manager for inactive things (e.g., `active_objects`).

**Comment by cjdd3b** [comment]
Let's discuss this with Sarah before we fully implement. I'll set up a meeting for this week or next.

**Comment by cjdd3b** [comment]
Alrighty. The idea here is that we want to handle amendments a bit differently from the existing app. That manifests in three key ways:

  - Amendments shouldn't delete itemizations from the filing they amend. They should mark them as inactive and/or superseded by an amendment instead. The purpose is to retain an audit trail, should we need it.
  - That logic should be consistent across different schedule types. Expenditures and contributions should be handled the same way, which is to say no deleting for either of them.
  - Summary totals in the committee tables, however, should reflect any new totals that come in from an amendment. If Jeb says he raised $10M year-to-date in October, and then amends that to say he raised $11M, the summary total we retain for him should be $11M.

We also need some kind of a system to carry over donor IDs from amended filings to amendments. I think this is the DonorContribution table Bowers mentioned above.

Here's a rough sketch of how this might play out in logic. When an amendment is loaded:

Filings table:
  - [ ] Load the filing object into the filings table
  - [ ] is_amendment should be set to true on the amendment
  - [ ] superseded_by_amendment should be set to true on the filing the amendment amends  

Itemizations:
  - [ ] Load all itemization schedules (A, E, etc.) into their respective tables
  - [ ] superseded_by_amendment should be set to true on records the filing amends. I think you can be safe just grabbing all the records in the amended filing and flipping this in bulk, but worth verifying.
  - [ ] active should be set to false on the amended records as well

Committees table:
  - [ ] Supersede all coversheet totals with records from the amendment. One thing that could be weird here is load order. You want the most recent filing from the most recent filing period to be the one reflected by the totals. It's not unusual for someone to file in July, file in October, then file a July amendment AFTER the October filing. In that case, the October filing would be the most recent filing and therefore the one that should be reflected in the totals. This sounds brain-bending to me, so happy to talk it through when you get there.

Donor IDs:
  - [ ] Check with Bowers on whatever this DonorContribution logic was supposed to be. I think it involved a table with fields for candidate ID, transaction ID and donor ID.

**Comment by rshorey** [comment]
@cjdd3b for the purposes of reconstructing history, do we care about reasons transactions might be marked inactive? We mark transactions inactive if they are duplicates (for example, skedEs' that appear in both 24 hour reports and quarterly filings), for amended filings, and maybe other reasons. Should I add some field to indicate why?

**Comment by rshorey** [comment]
re the most recent totals for committee thing, I'm sorting the filings by coverage_to and then filed_date and taking the most recent one that comes with totals (to avoid 24hr reports or whatever). I thin this'll work because it'll get the one with latest coverage that was filed most recently, so an amendment will correctly knock out the original version, but an amendment to an old filing won't knock out a newer filing. Do you see any problems with that logic? I agree it's confusing and thus worth double checking.

**Comment by cjdd3b** [comment]
That sounds like it makes sense, but we should just be sure to check it
closely.

**Comment by rshorey** [comment]
- [ ] when amendment is deleted, reinstate transactions from filing it amended.

**Comment by rshorey** [comment]
@cjdd3b (no hurry, not doing till Monday), do you think there's ever a situation where we'd need to delete a filing without reloading it? because if we end up with a filing that was amended and then superseded we're in for an absolute nightmare. For a whole committee this is fine (we just zero everything out), but if we don't think the single filing is going to happen, I'd like to make a reload_filing command instead of delete_filing.

I can figure it out if it seems like we need this, but ugh!

**Comment by cjdd3b** [comment]
I think reload is fine. The only reason I can think of to delete a filing
is if something goes wrong when it loads.
