### ISSUE TITLE
Handle backreferences

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#26]
Similar to #14. Also pending a meeting with Sarah.

**Comment by cjdd3b** [comment]
Here's some of the [logic](https://github.com/newsdev/campaign_finance/blob/2016/lib/itemization_processor.rb#L85-L166) Derek used for this.

**Comment by rshorey** [comment]
- [ ] process skedb backreferences
- [ ] process skeda backreferences
- [ ] write tests

**Comment by rshorey** [comment]
we might not be doing anything with skedA's. Sounds like we currently don't include memo fields in any calculations. If we want to continue with this, we should be fine, but if we want to do something about marking some of these inactive, it's a way more complicated conversation that we haven't fully covered on the google doc.

**Comment by rshorey** [comment]
The current plan is to deactivate any transaction with a memo.

**Comment by rshorey** [comment]
I believe the way things are currently being done, summing should work for skedA's. I'm going to close this issue until/unless we run into any problems. We are going to have to be careful about negative contributions, since they're involved in reallocation. But we have to be careful of them anyway because we're now processing refunds as negative contribs.
